FROM node:16 as build-stage
WORKDIR /app/frontend
ENV PATH /app/frontend/node_modules/.bin:$PATH
# COPY package.json /app/package.json
COPY package*.json ./
RUN npm install --silent
# RUN npm install @vue/cli@3.7.0 -g
RUN npm install -g @vue/cli
COPY . /app/frontend
RUN npm run build


FROM nginx as production-stage
COPY --from=build-stage /app/frontend/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]